### ISSUE TITLE
create-payment: Required 'profile id' is missing

### ISSUE THREAD

**Issue by itsoft7** [sverraest/revolut-php#17]
Hello

$client->payments->create($p_arr);

Client error: resulted in a response: {"message":"Required 'profile id' is missing","code":2101}

https://revolut-engineering.github.io/api-docs/business-api/#api-reference-api-reference-payments-create-payment

There is no field 'profile id'. :(((

**Comment by itsoft7** [comment]
curl -X POST https://b2b.revolut.com/api/1.0/pay   -H "Authorization: Bearer oa_prod_*******"   --data @- << EOF
{"schedule_for":"2020-11-09","amount":"339.07","currency":"EUR","account_id":"e98e2adf-bf44-40b6-a73d-2d0acf3836cb","receiver":{"counterparty_id":"2e963a86-59b5-45ea-816d-7619ad7406e2","account_id":"a88014cf-32cb-4210-b738-bcc304b7c742"},"reference":"SI1996062690-40002 TAXS Dohodnina (10.20)","request_id":"7e6899af6e6199b7153c83beb72fa1d9"}

EOF
{"message":"Required 'profile id' is missing","code":2101}

**Comment by sverraest** [comment]
@itsoft7 Are you sending a profile id? We're not doing any mapping so if you're not sending it and Revolut is expecting it you should add it to your payload.

**Comment by netwick** [comment]
Hello sverraest,

First of all, happy new year !

I have the same probleme as itsoft7, and done many researches to find how to compose a payload with "profile id" field
But no success ... i don't see where to add this information  (syntax, position ?)

Could you post a sample of payload please ?
I would be very helpful :-)

Many thanks by advance

Eric

**Comment by chrisob55** [comment]
In case anyone else has this issue, the fix for me was to remove the "schedule_for" field from the payload.

**Comment by atvvarna** [comment]
Hello,

I didn't use "schedule_for" but I've got the same error.
Any tips?
