### ISSUE TITLE
Guzzle 7

### ISSUE THREAD

**Issue by miroslav-marinkovic** [sverraest/revolut-php#18]
Hi, we've been using your package to sync Revolut transactions into our system for a while now. Our application is built on top of Laravel 7. Laravel 7 is now deprecated (https://laravelversions.com/7), and we are switching to Laravel 8. Problem emerges from Laravel 8's requirement of Guzzle 7 (https://laravel.com/docs/8.x/upgrade#updating-dependencies) and we cannot upgrade any time soon unless we replace your package which might prove to be a lot more work than we estimated. Since Guzzle 7 is already in version 7.2, do you plan on supporting it?

**Comment by sverraest** [comment]
Hi @miroslav-marinkovic will be working on upgrading this and adding the new functionality in the API in the coming weeks.

**Comment by sverraest** [comment]
Solved in https://github.com/sverraest/revolut-php/pull/19
